p8105\_hw3\_xm2229
================
Xiaoyue Ma
10/13/2019

# Problem 1

load the data set from the
    library

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.2.1     ✔ purrr   0.3.2
    ## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
    ## ✔ tidyr   1.0.0     ✔ stringr 1.4.0
    ## ✔ readr   1.3.1     ✔ forcats 0.4.0

    ## ── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(p8105.datasets)
data("instacart")
```

The goal is to do some exploration of this dataset. To that end, write a
short description of the dataset, noting the size and structure of the
data, describing some key variables, and giving illstrative examples of
observations. Then, do or answer the following (commenting on the
results of each):

  - How many aisles are there, and which aisles are the most items
    ordered from?

<!-- end list -->

``` r
skimr::skim(instacart)
```

    ## Skim summary statistics
    ##  n obs: 1384617 
    ##  n variables: 15 
    ## 
    ## ── Variable type:character ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ##      variable missing complete       n min max empty n_unique
    ##         aisle       0  1384617 1384617   3  29     0      134
    ##    department       0  1384617 1384617   4  15     0       21
    ##      eval_set       0  1384617 1384617   5   5     0        1
    ##  product_name       0  1384617 1384617   3 159     0    39123
    ## 
    ## ── Variable type:integer ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ##                variable missing complete       n       mean        sd p0
    ##       add_to_cart_order       0  1384617 1384617       8.76      7.42  1
    ##                aisle_id       0  1384617 1384617      71.3      38.1   1
    ##  days_since_prior_order       0  1384617 1384617      17.07     10.43  0
    ##           department_id       0  1384617 1384617       9.84      6.29  1
    ##               order_dow       0  1384617 1384617       2.7       2.17  0
    ##       order_hour_of_day       0  1384617 1384617      13.58      4.24  0
    ##                order_id       0  1384617 1384617 1706297.62 989732.65  1
    ##            order_number       0  1384617 1384617      17.09     16.61  4
    ##              product_id       0  1384617 1384617   25556.24  14121.27  1
    ##               reordered       0  1384617 1384617       0.6       0.49  0
    ##                 user_id       0  1384617 1384617   1e+05     59487.15  1
    ##     p25     p50     p75    p100     hist
    ##       3       7      12      80 ▇▃▁▁▁▁▁▁
    ##      31      83     107     134 ▃▇▃▃▇▅▅▆
    ##       7      15      30      30 ▂▅▃▃▁▂▁▇
    ##       4       8      16      21 ▃▇▂▁▂▆▁▃
    ##       1       3       5       6 ▇▅▃▃▁▃▅▅
    ##      10      14      17      23 ▁▁▃▇▇▇▅▂
    ##  843370 1701880 2568023 3421070 ▇▇▇▇▇▇▇▇
    ##       6      11      21     100 ▇▂▁▁▁▁▁▁
    ##   13380   25298   37940   49688 ▆▆▇▇▇▆▇▇
    ##       0       1       1       1 ▆▁▁▁▁▁▁▇
    ##   51732   1e+05  154959  206209 ▇▇▇▇▇▇▇▇

**The dataset is derived from the original “instacart” data. The dataset
has 1384617 rows and 15 columns. The structure of the data is tbl\_df,
tbl, data.frame. Variables include order\_id, product\_id,
add\_to\_cart\_order, reordered, user\_id, eval\_set, order\_number,
order\_dow, order\_hour\_of\_day, days\_since\_prior\_order,
product\_name, aisle\_id, department\_id, aisle, department. Key
variables descriptions can be find on**
<http://p8105.com/dataset_instacart.html>:

  - order\_id: order identifier
  - product\_id: product identifier
  - add\_to\_cart\_order: order in which each product was added to cart
  - reordered: 1 if this prodcut has been ordered by this user in the
    past, 0 otherwise
  - user\_id: customer identifier
  - eval\_set: which evaluation set this order belongs in (Note that the
    data for use in this class is exclusively from the “train”
    eval\_set)
  - order\_number: the order sequence number for this user (1=first,
    n=nth)
  - order\_dow: the day of the week on which the order was placed
  - order\_hour\_of\_day: the hour of the day on which the order was
    placed
  - days\_since\_prior\_order: days since the last order, capped at 30,
    NA if order\_number=1
  - product\_name: name of the product
  - aisle\_id: aisle identifier
  - department\_id: department identifier
  - aisle: the name of the aisle
  - department: the name of the department

**Here are some exmaples of some observations in from the dataset:**

``` r
head(instacart, 5)
```

    ## # A tibble: 5 x 15
    ##   order_id product_id add_to_cart_ord… reordered user_id eval_set
    ##      <int>      <int>            <int>     <int>   <int> <chr>   
    ## 1        1      49302                1         1  112108 train   
    ## 2        1      11109                2         1  112108 train   
    ## 3        1      10246                3         0  112108 train   
    ## 4        1      49683                4         0  112108 train   
    ## 5        1      43633                5         1  112108 train   
    ## # … with 9 more variables: order_number <int>, order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>,
    ## #   product_name <chr>, aisle_id <int>, department_id <int>, aisle <chr>,
    ## #   department <chr>

  - Make a plot that shows the number of items ordered in each aisle,
    limiting this to aisles with more than 10000 items ordered. Arrange
    aisles sensibly, and organize your plot so others can read it.

**There are 134 aisles and aisle \#83, which is the fresh vegetables
aisle.**

``` r
library(ggplot2)
instacart %>%
  count(aisle, name = "n_orders") %>%
  filter(n_orders >= 10000) %>%
  ggplot(aes(x = aisle, y= n_orders)) + 
  geom_bar(position = "dodge", stat = "identity") + coord_flip()
```

![](p8105_hw3_xm2229_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

  - Make a table showing the three most popular items in each of the
    aisles “baking ingredients”, “dog food care”, and “packaged
    vegetables fruits”. Include the number of times each item is ordered
    in your table.

<!-- end list -->

``` r
instacart %>% 
  filter(aisle == "baking ingredients" | aisle == "dog food care" | aisle == "packaged vegetables fruits") %>%
  group_by(aisle, product_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count), .by_group = TRUE) %>%
  group_by(aisle) %>%
  slice(1:3) %>%
  knitr::kable()
```

| aisle                      | product\_name                                 | count |
| :------------------------- | :-------------------------------------------- | ----: |
| baking ingredients         | Light Brown Sugar                             |   499 |
| baking ingredients         | Pure Baking Soda                              |   387 |
| baking ingredients         | Cane Sugar                                    |   336 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |    30 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |    28 |
| dog food care              | Small Dog Biscuits                            |    26 |
| packaged vegetables fruits | Organic Baby Spinach                          |  9784 |
| packaged vegetables fruits | Organic Raspberries                           |  5546 |
| packaged vegetables fruits | Organic Blueberries                           |  4966 |

  - Make a table showing the mean hour of the day at which Pink Lady
    Apples and Coffee Ice Cream are ordered on each day of the week;
    format this table for human readers (i.e. produce a 2 x 7 table).

<!-- end list -->

``` r
instacart %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  group_by(product_name, order_dow) %>% 
  summarise(mean_hour = mean(order_hour_of_day)) %>% 
  spread(key = order_dow, value = mean_hour) %>% # produce a 2*7 table
  knitr::kable(digits = 2)
```

| product\_name    |     0 |     1 |     2 |     3 |     4 |     5 |     6 |
| :--------------- | ----: | ----: | ----: | ----: | ----: | ----: | ----: |
| Coffee Ice Cream | 13.77 | 14.32 | 15.38 | 15.32 | 15.22 | 12.26 | 13.83 |
| Pink Lady Apples | 13.44 | 11.36 | 11.70 | 14.25 | 11.55 | 12.78 | 11.94 |

# Problem 2

Load in the dataset

``` r
data("brfss_smart2010")
```

First, do some data cleaning:

  - format the data to use appropriate variable names;
  - focus on the “Overall Health” topic
  - include only responses from “Excellent” to “Poor”
  - organize responses as a factor taking levels ordered from “Poor” to
    “Excellent”

<!-- end list -->

``` r
brfss = brfss_smart2010 %>% 
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>% 
  mutate(response = forcats::fct_relevel(response, c("Excellent", "Very good", "Good", "Fair", "Poor")))

head(brfss)
```

    ## # A tibble: 6 x 23
    ##    year locationabbr locationdesc class topic question response sample_size
    ##   <int> <chr>        <chr>        <chr> <chr> <chr>    <fct>          <int>
    ## 1  2010 AL           AL - Jeffer… Heal… Over… How is … Excelle…          94
    ## 2  2010 AL           AL - Jeffer… Heal… Over… How is … Very go…         148
    ## 3  2010 AL           AL - Jeffer… Heal… Over… How is … Good             208
    ## 4  2010 AL           AL - Jeffer… Heal… Over… How is … Fair             107
    ## 5  2010 AL           AL - Jeffer… Heal… Over… How is … Poor              45
    ## 6  2010 AL           AL - Mobile… Heal… Over… How is … Excelle…          91
    ## # … with 15 more variables: data_value <dbl>, confidence_limit_low <dbl>,
    ## #   confidence_limit_high <dbl>, display_order <int>,
    ## #   data_value_unit <chr>, data_value_type <chr>,
    ## #   data_value_footnote_symbol <chr>, data_value_footnote <chr>,
    ## #   data_source <chr>, class_id <chr>, topic_id <chr>, location_id <chr>,
    ## #   question_id <chr>, respid <chr>, geo_location <chr>

Using this dataset, do or answer the following (commenting on the
results of each):

  - In 2002, which states were observed at 7 or more locations? What
    about in 2010?

<!-- end list -->

``` r
answer = brfss %>% 
  filter(year == 2002) %>% 
  group_by(locationabbr) %>% 
  summarise(n = n_distinct(locationdesc)) %>% 
  filter(n >= 7)
```

**In 2002 CT, FL, MA, NC, NJ, PA were observed at 7 or more locations.**

``` r
answer_2010 = brfss %>% 
  filter(year == 2010) %>% 
  group_by(locationabbr) %>% 
  summarise(n = n_distinct(locationdesc)) %>% 
  filter(n >= 7)
```

**In 2010 CA, CO, FL, MA, MD, NC, NE, NJ, NY, OH, PA, SC, TX, WA were
observed at 7 or more locations.**

  - Construct a dataset that is limited to Excellent responses, and
    contains, year, state, and a variable that averages the data\_value
    across locations within a state. Make a “spaghetti” plot of this
    average value over time within a state (that is, make a plot showing
    a line for each state across years – the geom\_line geometry and
    group aesthetic will help).

<!-- end list -->

``` r
brfss %>%
  filter(response == "Excellent") %>%
  group_by(year, locationabbr) %>%
  summarise(average_v = mean(data_value)) %>%
  ggplot(aes(x = locationabbr, y = average_v, color = year)) + 
  geom_line() +
  labs(
    title = "Mean data value in each state from 2002 to 2010",
    x = "State",
    y = "Number of locations"
  ) + coord_flip()
```

    ## Warning: Removed 3 rows containing missing values (geom_path).

![](p8105_hw3_xm2229_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->

  - Make a two-panel plot showing, for the years 2006, and 2010,
    distribution of data\_value for responses (“Poor” to “Excellent”)
    among locations in NY State.

<!-- end list -->

``` r
brfss %>%
  filter(locationabbr == "NY", year %in% c(2006, 2010)) %>%
  ggplot(aes(x = data_value, fill = response)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue") +
  labs(
    title = "Density distribution of data_value for year 2006 and 2010",
    x = "data_value",
    y = "density"
  )+
  facet_grid(~year)
```

![](p8105_hw3_xm2229_files/figure-gfm/unnamed-chunk-12-1.png)<!-- -->

# Problem 3

load in the dataset

``` r
accel <- read.csv('./data/accel_data.csv')
```

  - Load, tidy, and otherwise wrangle the data. Your final dataset
    should include all originally observed variables and values; have
    useful variable names; include a weekday vs weekend variable; and
    encode data with reasonable variable classes. Describe the resulting
    dataset (e.g. what variables exist, how many observations, etc).

<!-- end list -->

``` r
accel_cleaned = accel %>% 
  janitor::clean_names() %>%
  mutate(weekdays = ifelse(day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), "weekday", "weekend")) %>%
  mutate(weekdays = forcats::fct_relevel(weekdays, c("weekday", "weekend")))
```

**The dataset is derived from the heart activity collected from an
accelerometer of a patient in weeks. The dataset has 35 rows and 1444
columns. The structure of the data is data.frame. Key variables are: **

  - week: number of week since the data collection begins

  - day\_id: day identifier

  - day: day of the week when the data is collected

  - weekdays: 1 if it is a weekday, 0 otherwise.

  - activity\_\* : are the activity counts for each minute of a 24-hour
    day starting at midnight

  - Traditional analyses of accelerometer data focus on the total
    activity over the day. Using your tidied dataset, aggregate accross
    minutes to create a total activity variable for each day, and create
    a table showing these totals. Are any trends apparent?

<!-- end list -->

``` r
accel_cleaned %>%
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity",
    values_to = "activity_sum"
  ) %>%
  group_by(day_id) %>%
  summarise(
    day_activity = sum(activity_sum)
    ) %>%
  knitr::kable()
```

| day\_id | day\_activity |
| ------: | ------------: |
|       1 |     480542.62 |
|       2 |      78828.07 |
|       3 |     376254.00 |
|       4 |     631105.00 |
|       5 |     355923.64 |
|       6 |     307094.24 |
|       7 |     340115.01 |
|       8 |     568839.00 |
|       9 |     295431.00 |
|      10 |     607175.00 |
|      11 |     422018.00 |
|      12 |     474048.00 |
|      13 |     423245.00 |
|      14 |     440962.00 |
|      15 |     467420.00 |
|      16 |     685910.00 |
|      17 |     382928.00 |
|      18 |     467052.00 |
|      19 |     371230.00 |
|      20 |     381507.00 |
|      21 |     468869.00 |
|      22 |     154049.00 |
|      23 |     409450.00 |
|      24 |       1440.00 |
|      25 |     260617.00 |
|      26 |     340291.00 |
|      27 |     319568.00 |
|      28 |     434460.00 |
|      29 |     620860.00 |
|      30 |     389080.00 |
|      31 |       1440.00 |
|      32 |     138421.00 |
|      33 |     549658.00 |
|      34 |     367824.00 |
|      35 |     445366.00 |

**There is no apparent trend**

  - Accelerometer data allows the inspection activity over the course of
    the day. Make a single-panel plot that shows the 24-hour activity
    time courses for each day and use color to indicate day of the week.
    Describe in words any patterns or conclusions you can make based on
    this graph.

<!-- end list -->

``` r
accel_cleaned %>%
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity",
    values_to = "activity_sum"
  ) %>%
  group_by(day_id, day) %>%
  summarise(
    day_activity = sum(activity_sum)
    ) %>%
  ggplot(aes(x = day_id, y=day_activity, color=day)) + 
  geom_point() + 
  geom_line() + 
  labs(
    title = "24-hour activity for each day",
    x = "day",
    y = "24-hour activity"
  )
```

![](p8105_hw3_xm2229_files/figure-gfm/unnamed-chunk-16-1.png)<!-- -->

**According to the plot, it seems to be a peak activity in the first
three weeks and a drop in the fourth and fifth week following a rise in
the end.**
